[project]
name = "mutmut-pyproject"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "mutmut>=3.2.2",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
